package com.tosh.iptvplayer.data

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Stores small strings encrypted with an AES-256-GCM key that lives in the Android Keystore (the
 * key material never leaves it), in an ordinary SharedPreferences file. Replaces
 * EncryptedSharedPreferences, which Google has deprecated: that library wraps a Tink keyset that
 * could become undecryptable independently of the data (the crash-at-startup case), whereas here
 * a value that can't be decrypted is simply treated as absent.
 *
 * Each value is stored as Base64(iv + ciphertext); the IV is generated by the Keystore for every
 * write, as GCM requires it to never repeat under one key.
 */
internal class SecureStore(context: Context, prefsName: String, private val keyAlias: String) {

    private val prefs = context.getSharedPreferences(prefsName, Context.MODE_PRIVATE)

    fun getString(name: String): String? {
        val stored = prefs.getString(name, null) ?: return null
        return runCatching {
            val bytes = Base64.decode(stored, Base64.NO_WRAP)
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                key(),
                GCMParameterSpec(GCM_TAG_BITS, bytes, 0, GCM_IV_BYTES)
            )
            String(cipher.doFinal(bytes, GCM_IV_BYTES, bytes.size - GCM_IV_BYTES), Charsets.UTF_8)
        }.getOrElse {
            // Key gone or reset (e.g. data restored to another device) or the value is corrupt:
            // it can never be read again, so drop it and carry on as if it had never been saved
            // rather than failing every later read.
            prefs.edit().remove(name).apply()
            null
        }
    }

    fun putString(name: String, value: String) {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        val encrypted = cipher.iv + cipher.doFinal(value.toByteArray(Charsets.UTF_8))
        prefs.edit().putString(name, Base64.encodeToString(encrypted, Base64.NO_WRAP)).apply()
    }

    fun remove(name: String) {
        prefs.edit().remove(name).apply()
    }

    /** Returns the existing Keystore key, creating it on first use (or after it went missing). */
    private fun key(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getKey(keyAlias, null) as? SecretKey)?.let { return it }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                keyAlias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_IV_BYTES = 12
        const val GCM_TAG_BITS = 128
    }
}
